// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzaklR58z35wixnrvzsW3Q5gX--KWUMG4',
    appId: '1:534510474855:web:6bc0d40f03883aae0e66c2',
    messagingSenderId: '534510474855',
    projectId: 'flutter14-6d1b1',
    authDomain: 'flutter14-6d1b1.firebaseapp.com',
    storageBucket: 'flutter14-6d1b1.firebasestorage.app',
    measurementId: 'G-D219XNGTS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxxca4lgKTnwa-RF4iiObHa3-mL5Mg98Q',
    appId: '1:534510474855:android:5d9285fe2fa54c170e66c2',
    messagingSenderId: '534510474855',
    projectId: 'flutter14-6d1b1',
    storageBucket: 'flutter14-6d1b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWvXyhpKco5mAL_ebvY3VT_nk4FC8YqfI',
    appId: '1:534510474855:ios:cefbff1c4432a7460e66c2',
    messagingSenderId: '534510474855',
    projectId: 'flutter14-6d1b1',
    storageBucket: 'flutter14-6d1b1.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWvXyhpKco5mAL_ebvY3VT_nk4FC8YqfI',
    appId: '1:534510474855:ios:cefbff1c4432a7460e66c2',
    messagingSenderId: '534510474855',
    projectId: 'flutter14-6d1b1',
    storageBucket: 'flutter14-6d1b1.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzaklR58z35wixnrvzsW3Q5gX--KWUMG4',
    appId: '1:534510474855:web:19b75720fb294cb90e66c2',
    messagingSenderId: '534510474855',
    projectId: 'flutter14-6d1b1',
    authDomain: 'flutter14-6d1b1.firebaseapp.com',
    storageBucket: 'flutter14-6d1b1.firebasestorage.app',
    measurementId: 'G-0MHHTTPH6C',
  );
}
